/// Locally bundled editorial covers, keyed by stable content ID.
/// New server articles can continue to supply their own image URL.
const articleCoverAssets = <String, String>{
  'klasik-sporcu-icecegi': 'assets/explore/klasik-sporcu-icecegi.webp',
  'akcaagacli-elektrolit': 'assets/explore/akcaagacli-elektrolit.webp',
  'hizli-hidrasyon': 'assets/explore/hizli-hidrasyon.webp',
  'hindistan-cevizi-turuncgil':
      'assets/explore/hindistan-cevizi-turuncgil.webp',
  'salatalik-lime': 'assets/explore/salatalik-lime.webp',
  'portakal-zencefil': 'assets/explore/portakal-zencefil.webp',
  'karpuzlu-potasyum': 'assets/explore/karpuzlu-potasyum.webp',
  'uzum-limon': 'assets/explore/uzum-limon.webp',
  'hurmali-kakao': 'assets/explore/hurmali-kakao.webp',
  'yesil-cay-sporcu': 'assets/explore/yesil-cay-sporcu.webp',
  'cilekli-kefir': 'assets/explore/cilekli-kefir.webp',
  'yaban-mersinli-antioksidan':
      'assets/explore/yaban-mersinli-antioksidan.webp',
  'muzlu-tarcinli-smoothie': 'assets/explore/muzlu-tarcinli-smoothie.webp',
  'espresso-tarcin': 'assets/explore/espresso-tarcin.webp',
  'kakaolu-enerji-shotu': 'assets/explore/kakaolu-enerji-shotu.webp',
  'ozempic-ne-biliyoruz': 'assets/explore/ozempic-ne-biliyoruz.webp',
  'sporcu-beslenmesi-temeller':
      'assets/explore/sporcu-beslenmesi-temeller.webp',
  'sporun-gune-etkisi': 'assets/explore/sporun-gune-etkisi.webp',
  'bagirsak-diyetleri': 'assets/explore/bagirsak-diyetleri.webp',
  'sporcu-icecegi-rehberi': 'assets/explore/sporcu-icecegi-rehberi.webp',
  'protein-cesitlendirme': 'assets/explore/protein-cesitlendirme.webp',
  'lor-kasesi': 'assets/explore/lor-kasesi.webp',
  'edamame-nohut': 'assets/explore/edamame-nohut.webp',
  'firinda-tofu-kinoa': 'assets/explore/firinda-tofu-kinoa.webp',
  'ton-fasulye-piyaz': 'assets/explore/ton-fasulye-piyaz.webp',
  'tuzlu-yulaf': 'assets/explore/tuzlu-yulaf.webp',
  'kefirli-protein-smoothie': 'assets/explore/kefirli-protein-smoothie.webp',
  'uzun-nefes-verme': 'assets/explore/uzun-nefes-verme.webp',
  'zihin-nerede': 'assets/explore/zihin-nerede.webp',
  'uykuya-hazirlik': 'assets/explore/uykuya-hazirlik.webp',
  'zihnin-dolu': 'assets/explore/zihnin-dolu.webp',
  'beden-taramasi': 'assets/explore/beden-taramasi.webp',
  'kacirdigin-gun': 'assets/explore/kacirdigin-gun.webp',
  'dort-gun': 'assets/explore/dort-gun.webp',
  'ne-zaman-yaparim': 'assets/explore/ne-zaman-yaparim.webp',
  'odak-mi-acik-mi': 'assets/explore/odak-mi-acik-mi.webp',
  'yururken': 'assets/explore/yururken.webp',
  'poz-meselesi': 'assets/explore/poz-meselesi.webp',
  'iki-dakikalik-sifirlama': 'assets/explore/iki-dakikalik-sifirlama.webp',
  'sefkat-pratigi': 'assets/explore/sefkat-pratigi.webp',
  'sabah-mi-aksam-mi': 'assets/explore/sabah-mi-aksam-mi.webp',
  'uygulamasiz-devam': 'assets/explore/uygulamasiz-devam.webp',
  'on-dakika-kurali': 'assets/explore/on-dakika-kurali.webp',
  'yedi-bin-adim': 'assets/explore/yedi-bin-adim.webp',
  'en-iyi-egzersiz': 'assets/explore/en-iyi-egzersiz.webp',
  'agirlik-kaldirmak': 'assets/explore/agirlik-kaldirmak.webp',
  'isinma-gerekli-mi': 'assets/explore/isinma-gerekli-mi.webp',
  'kas-agrisi': 'assets/explore/kas-agrisi.webp',
  'evde-ekipmansiz': 'assets/explore/evde-ekipmansiz.webp',
  'merdiven': 'assets/explore/merdiven.webp',
  'haftada-kac-gun': 'assets/explore/haftada-kac-gun.webp',
  'motivasyon-beklemek': 'assets/explore/motivasyon-beklemek.webp',
  'oturmayi-bolmek': 'assets/explore/oturmayi-bolmek.webp',
  'fazla-hevesle-baslamak': 'assets/explore/fazla-hevesle-baslamak.webp',
  'iki-saat-doga': 'assets/explore/iki-saat-doga.webp',
  'yalnizlik-ve-saglik': 'assets/explore/yalnizlik-ve-saglik.webp',
  'ayni-saatte-kalkmak': 'assets/explore/ayni-saatte-kalkmak.webp',
  'ekran-ve-uyku': 'assets/explore/ekran-ve-uyku.webp',
  'dus-riteli': 'assets/explore/dus-riteli.webp',
  'hayir-demek': 'assets/explore/hayir-demek.webp',
  'dinlenme-turleri': 'assets/explore/dinlenme-turleri.webp',
  'sabahin-ilk-yirmi-dakikasi':
      'assets/explore/sabahin-ilk-yirmi-dakikasi.webp',
  'bes-dakikalik-toparlama': 'assets/explore/bes-dakikalik-toparlama.webp',
  'gunes-koruyucu': 'assets/explore/gunes-koruyucu-v2.webp',
  'sade-cilt-rutini': 'assets/explore/sade-cilt-rutini.webp',
  'mikro-molalar': 'assets/explore/mikro-molalar.webp',
  'duygusal-yorgunluk': 'assets/explore/duygusal-yorgunluk.webp',
  'kendine-randevu': 'assets/explore/kendine-randevu.webp',
  'bildirimleri-kapatmak': 'assets/explore/bildirimleri-kapatmak.webp',
  'sosyal-medya-akisi': 'assets/explore/sosyal-medya-akisi-v2.webp',
  'sessizlik': 'assets/explore/sessizlik.webp',
  'yardim-istemek': 'assets/explore/yardim-istemek.webp',
  'altmis-alti-gun': 'assets/explore/altmis-alti-gun-v2.webp',
  'on-bin-saat': 'assets/explore/on-bin-saat-v2.webp',
  'erteleme': 'assets/explore/erteleme.webp',
  'iki-dakika': 'assets/explore/iki-dakika-v2.webp',
  'kimlik-ve-aliskanlik': 'assets/explore/kimlik-ve-aliskanlik.webp',
  'hedef-degil-sistem': 'assets/explore/hedef-degil-sistem.webp',
  'haftalik-gozden-gecirme': 'assets/explore/haftalik-gozden-gecirme.webp',
  'karar-yorgunlugu': 'assets/explore/karar-yorgunlugu.webp',
  'derin-calisma': 'assets/explore/derin-calisma.webp',
  'ogrenmeyi-ogrenmek': 'assets/explore/ogrenmeyi-ogrenmek.webp',
  'not-almak': 'assets/explore/not-almak.webp',
  'geri-bildirim': 'assets/explore/geri-bildirim.webp',
  'karsilastirma': 'assets/explore/karsilastirma.webp',
  'mukemmeliyetcilik': 'assets/explore/mukemmeliyetcilik.webp',
  'basarisizliktan-sonra': 'assets/explore/basarisizliktan-sonra.webp',
  'zaman-tahmini': 'assets/explore/zaman-tahmini.webp',
  'gunun-uc-isi': 'assets/explore/gunun-uc-isi.webp',
  'takvimi-savunmak': 'assets/explore/takvimi-savunmak.webp',
  'okuma-aliskanligi': 'assets/explore/okuma-aliskanligi.webp',
  'merak-listesi': 'assets/explore/merak-listesi.webp',
  'konfor-alani': 'assets/explore/konfor-alani.webp',
  'tavsiye-secmek': 'assets/explore/tavsiye-secmek.webp',
  'birikimli-etki': 'assets/explore/birikimli-etki.webp',
  'enerji-yonetimi': 'assets/explore/enerji-yonetimi.webp',
  'kim-olmak-istiyorsun': 'assets/explore/kim-olmak-istiyorsun.webp',
  'islenmis-gida-farki': 'assets/explore/islenmis-gida-farki.webp',
  'lif-meselesi': 'assets/explore/lif-meselesi.webp',
  'tabak-duzeni': 'assets/explore/tabak-duzeni.webp',
  'yavas-ye': 'assets/explore/yavas-ye.webp',
  'kahvalti-sart-mi': 'assets/explore/kahvalti-sart-mi.webp',
  'siviyla-gelen-kalori': 'assets/explore/siviyla-gelen-kalori.webp',
  'aksam-atistirmasi': 'assets/explore/aksam-atistirmasi.webp',
  'etiket-okuma': 'assets/explore/etiket-okuma.webp',
  'disarida-yemek': 'assets/explore/disarida-yemek.webp',
  'su-ne-kadar': 'assets/explore/su-ne-kadar.webp',
  'cirpilmis-peynir-tost': 'assets/explore/cirpilmis-peynir-tost.webp',
  'firinda-yulaf': 'assets/explore/firinda-yulaf.webp',
  'yesil-tanrica-kase': 'assets/explore/yesil-tanrica-kase.webp',
  'tahinli-hurma-smoothie': 'assets/explore/tahinli-hurma-smoothie.webp',
  'yogun-fasulye-salatasi': 'assets/explore/yogun-fasulye-salatasi.webp',
  'firinda-peynirli-makarna': 'assets/explore/firinda-peynirli-makarna.webp',
  'pancar-humusu': 'assets/explore/pancar-humusu.webp',
  'tepside-balli-tavuk': 'assets/explore/tepside-balli-tavuk.webp',
  'karpuz-peynir-salata': 'assets/explore/karpuz-peynir-salata.webp',
  'firinda-baharatli-nohut': 'assets/explore/firinda-baharatli-nohut.webp',
};
